### ISSUE TITLE
The table "patient_risk_assignment" for active record class "PatientRiskAssignment" cannot be found in the database. 

### ISSUE THREAD

**Issue by taylorsc17** [openeyes/OpenEyes#158]
I have newly installed openeyes I can get to some parts of the system but when searching for a patient the above error is presented. I am using the sample database but there does not seem to be a table for Patient_Risk_Assigemnt.

**Comment by bizmate** [comment]
have you run steps 21 and 22 of this document? https://github.com/openeyes/OpenEyes/wiki/OpenEyes-Installation

**Comment by vetusko** [comment]
there is an issue with the migration of that table, we'll fix it today!

**Comment by vetusko** [comment]
did you run all the migrations? did you receive any error messages?

**Comment by taylorsc17** [comment]
Im running on  a windows 7 system. I imported the sample sql file i have 327 tables, several with data but there is no patient_risk_assignment table.

**Comment by vetusko** [comment]
In that case you need to follow the steps what bizmate suggested:
"have you run steps 21 and 22 of this document? https://github.com/openeyes/OpenEyes/wiki/OpenEyes-Installation"

**Comment by taylorsc17** [comment]
Excellent I will run the migrations, I'm sure that will solve the problem. I followed the Win 7 instructions at https://github.com/openeyes/OpenEyes/wiki/Installing-OpenEyes-on-Windows-7-SP1

Could these instructions be updated to include a step for the migrations.

**Comment by taylorsc17** [comment]
I have ran the migrations all is now working correctly. Thank You.

**Comment by iceict** [comment]
I have just installed the new version with the test data attached using the win7 guide and I do get the same issue with the table "patient_risk_assignment" missing. 

I looked on the other installation document on steps 21 and 22, and when I type ./yiic migrate I just get /usr/bin/env: php: No such file or directory

Also tried to changed the file yiic.php in the protected folder since the code said 
/../vendor/yiisoft/yii/framework/yiic.php and since the yii folder in protected folder I changed it to 
$yiic = $dirname .'/yii/framework/yiic.php';

Any idea what I could be doing wrong?
How should I be able to create the missing table(s) and get some test data?

Thank you
Kind regards
Andreas
