### ISSUE TITLE
vagrant virtualbox name

### ISSUE THREAD

**Issue by splatEric** [openeyes/OpenEyes#388]
with the new vagrant build it would be good for the virtualbox instance name to reflect the path name that the project is cloned into to allow for easy traceability of multiple instances running or being configured.

**Comment by davidfsmith** [comment]
This issue is resolved by [90d331f](https://github.com/openeyes/OpenEyes/commit/90d331fb17d544f4b99b8d076fe9b8d895d39f7c) which allows for the passing in of a hostname and server name via the command line as documented in the Readme file.  The only issue is that the configuration options need to come before the vagrant command (this is noted)
